### ISSUE TITLE
High-Level: Set up basic React App

### ISSUE THREAD

**Issue by raroldan17** [FSA-TeamVenus/fsparty#4]
- [ ] make "create-player" field #5 
- [ ] make game selection/ creation field #6
- [x] make board that hosts all users #7
- [ ]  - main screen, create player screen, lobby screen, board
